apiVersion: apps/v1
kind: Deployment
metadata:
  name: mef-backend-deployment
  labels:
    app: mef-backend
spec:
  replicas: 3  # Desired number of replicas
  selector:
    matchLabels:
      app: mef-backend
  template:
    metadata:
      labels:
        app: mef-backend
    spec:
      containers:
      - name: mef-backend-container
        image: ayoub9le/mef_backend:tagname  # Replace with your Docker image name and tag
        ports:
        - containerPort: 9090  # Assuming your application runs on port 9090

apiVersion: v1
kind: Service
metadata:
  name: mef-backend-service
  labels:
    app: mef-backend
spec:
  type: NodePort  # Exposes the service on each Node's IP at a static port
  ports:
  - port: 9090  # Port to expose on the service
    targetPort: 9090  # Port on the pod
    nodePort: 30090  # Static port assigned on each node
  selector:
    app: mef-backend  # Selects the pods with this label to route traffic to

