apiVersion: v1
kind: Pod
metadata:
  name: mef-backend-pod
  labels:
    app: mef-backend
spec:
  containers:
  - name: mef-backend-container
    image: ayoub9le/mef_backend:latest
    ports:
    - containerPort: 9090
    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mef-backend-deployment
  labels:
    app: mef-backend
spec:
  replicas: 3  # Desired number of replicas
  selector:
    matchLabels:
      app: mef-backend
  template:
    metadata:
      labels:
        app: mef-backend
    spec:
      containers:
      - name: mef-backend-container
        image: ayoub9le/mef_backend:latest  # Replace with your Docker image name and tag
        ports:
        - containerPort: 9090
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-host:5432/electric_cars
            - name: SPRING_DATASOURCE_USERNAME
              value: mef
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SERVER_ERROR_INCLUDE_MESSAGE
              value: always
            - name: SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING
              value: "true"
            - name: SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS
              value: "false"
            - name: SERVER_PORT
              value: "9090"
            - name: SECURITY_JWT_TOKEN_SECRET_KEY
              value: my-secret-key
        

---
apiVersion: v1
kind: Service
metadata:
  name: mef-backend-service
  labels:
    app: mef-backend
spec:
  type: NodePort  # Exposes the service on each Node's IP at a static port
  ports:
  - port: 9090  # Port to expose on the service
    targetPort: 9090  # Port on the pod
    nodePort: 30090  # Static port assigned on each node
  selector:
    app: mef-backend  # Selects the pods with this label to route traffic to
