version: '3'

services:
  mef-backend:
    image: ayoub9le/mef_backend:latest
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/electric_cars
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:latest
    environment:
      POSTGRES_USER: mef
      POSTGRES_PASSWORD: password
      POSTGRES_DB: electric_cars
    ports:
      - "5432:5432"
